/**
 * Post-build prerender: turn each public route into a real HTML file.
 *
 * Cloudflare Pages serves a matching static asset before it consults `_redirects`,
 * so `dist/tools/dividend-portfolio-backtest/index.html` answers that path directly
 * and the SPA fallback (`/* /index.html 200`) still covers every other route.
 *
 * What a crawler gets afterwards: the route's own title/description/canonical/og,
 * its JSON-LD, its H1 and its full copy — instead of the homepage's head tags and
 * an empty <div id="root">.
 *
 * Naming matters: `<path>.html`, never `<path>/index.html`. Verified against
 * `wrangler pages dev` — Pages serves the `.html` sibling at the clean path
 * directly (200, no hop), while a directory index costs a 308 to the trailing-slash
 * form, which would also make each page's canonical URL a redirect target. Do NOT
 * add an explicit `_redirects` rule for these paths either: Pages strips `.html`
 * with a 308, so a `/tools/x -> /tools/x.html 200` rule becomes a redirect loop.
 * The SPA catch-all in public/_redirects still covers every client-routed path.
 *
 * Also emits sitemap.xml from the same PUBLIC_PAGES list, so adding a tool can't
 * silently leave the sitemap behind.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const dist = join(root, "dist");

const { renderRoute, PUBLIC_PAGES } = await import(join(root, "dist-ssr/entry-server.js"));

const SITE_URL = "https://sweetvaluelab.com";
const canonical = (path) => `${SITE_URL}${path}`;

const shell = readFileSync(join(dist, "index.html"), "utf8");
// The opening marker carries an explanatory comment, so match on the prefix.
const SEO_BLOCK = /<!-- seo:start[\s\S]*?seo:end -->/;
const ROOT_DIV = '<div id="root"></div>';
if (!SEO_BLOCK.test(shell)) throw new Error("prerender: index.html is missing the seo:start/seo:end block");
if (!shell.includes(ROOT_DIV)) throw new Error(`prerender: index.html is missing ${ROOT_DIV}`);

const escapeHtml = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const buildDate = new Date().toISOString().slice(0, 10);

function headFor(page) {
  const url = canonical(page.path);
  const graph = { "@context": "https://schema.org", "@graph": page.jsonLd };
  return [
    `<title>${escapeHtml(page.title)}</title>`,
    `<meta name="description" content="${escapeHtml(page.description)}" />`,
    `<link rel="canonical" href="${url}" />`,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="SweetValueLab" />`,
    `<meta property="og:title" content="${escapeHtml(page.title)}" />`,
    `<meta property="og:description" content="${escapeHtml(page.description)}" />`,
    `<meta property="og:url" content="${url}" />`,
    `<meta name="twitter:card" content="summary" />`,
    // JSON-LD closes with </script>, which cannot appear inside the string.
    `<script type="application/ld+json">${JSON.stringify(graph).replace(/</g, "\\u003c")}</script>`,
  ].join("\n    ");
}

for (const page of PUBLIC_PAGES) {
  const html = shell
    .replace(SEO_BLOCK, headFor(page))
    .replace(ROOT_DIV, `<div id="root">${renderRoute(page.path)}</div>`);
  // `<path>.html`, NOT `<path>/index.html`: Cloudflare Pages serves a directory
  // index only after a 308 to the trailing-slash form, which would leave every
  // visitor a redirect hop and — worse — make the canonical URL itself a redirect
  // target (`/tools/x` → `/tools/x/`, whose canonical says `/tools/x`). Verified
  // against `wrangler pages dev`: the `.html` sibling is served at the clean path
  // directly, 200, no hop.
  const out = page.path === "/" ? join(dist, "index.html") : join(dist, `${page.path.slice(1)}.html`);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, html);
  console.log(`prerendered ${page.path} → ${out.replace(dist, "dist")} (${(html.length / 1024).toFixed(1)} kB)`);
}

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by prerender/prerender.mjs from lib/seo.ts PUBLIC_PAGES. Do not edit. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${PUBLIC_PAGES.map(
  (p) => `  <url>
    <loc>${canonical(p.path)}</loc>
    <lastmod>${buildDate}</lastmod>
    <changefreq>${p.path === "/" ? "weekly" : "monthly"}</changefreq>
    <priority>${p.path === "/" ? "1.0" : "0.9"}</priority>
  </url>`,
).join("\n")}
</urlset>
`;
writeFileSync(join(dist, "sitemap.xml"), sitemap);
console.log(`generated sitemap.xml (${PUBLIC_PAGES.length} urls)`);
