/**
 * About — who runs this, where the numbers come from, and what it is not.
 *
 * Not filler: a research tool that shows people money figures owes them a plain
 * account of its sources and its limits, and a named operator behind it. Static
 * and prerendered like the rest of the public surface.
 */
import { useEffect } from "react";
import Link from "@/components/link";
import { ProsePage, Section, P, Ul, MailLink } from "@/components/public-chrome";
import { applySeo, ABOUT_SEO } from "@/lib/seo";

const REPO_URL = "https://github.com/allenyan513/quant-trading";

export default function AboutPage() {
  useEffect(() => applySeo(ABOUT_SEO), []);

  return (
    <ProsePage
      title="About SweetValueLab"
      intro={
        <>
          SweetValueLab is a facts layer for equity research — a set of deterministic tools that compute from primary data instead of
          summarizing opinions, plus an MCP connector that lets your own Claude read that data directly.
        </>
      }
    >
      <Section title="Who runs it">
        <P>
          SweetValueLab is built and operated independently by one person. There is no company behind it, no outside funding, and no sales
          team. The pipeline that powers it is open source — you can read exactly how every number is produced at{" "}
          <a href={REPO_URL} target="_blank" rel="noreferrer" style={{ color: "var(--accent)" }}>
            github.com/allenyan513/quant-trading
          </a>
          .
        </P>
      </Section>

      <Section title="Where the data comes from">
        <Ul>
          <li>
            <strong style={{ color: "var(--text)" }}>Financial Modeling Prep</strong> — daily split-adjusted prices, dividend history,
            company profiles, analyst estimates.
          </li>
          <li>
            <strong style={{ color: "var(--text)" }}>SEC EDGAR</strong> — filings read directly from the source: 13F holdings, 13D/G
            ownership, 8-K events, Form 4 insider transactions, and XBRL company facts.
          </li>
          <li>
            <strong style={{ color: "var(--text)" }}>Interactive Brokers Flex</strong> — only for signed-in users who connect their own
            account, and only read-only.
          </li>
        </Ul>
        <P>
          Filing data is stored point-in-time: a fact is recorded with the moment it became public, not the moment we fetched it, so a
          historical view shows what was actually knowable then.
        </P>
      </Section>

      <Section title="How the tools work">
        <P>
          The public tools are deterministic. Nothing on{" "}
          <Link href="/tools/dividend-portfolio-backtest" style={{ color: "var(--accent)" }}>
            the dividend backtester
          </Link>{" "}
          is generated by a language model — the same inputs always produce the same numbers, and each tool states its method on its own
          page. Where a model is involved elsewhere in the system, it classifies and prioritizes news; it never invents a price, a dividend
          or a return.
        </P>
      </Section>

      <Section title="What this is not">
        <P>
          It is not a broker, not a registered investment adviser, and not a source of personalized advice. Backtests are hypothetical: they
          exclude taxes, commissions and slippage, and past results say nothing about the future. Data comes from third parties and can be
          wrong or delayed. Decide for yourself, and verify anything that matters before acting on it.
        </P>
      </Section>

      <Section title="Contact">
        <P>
          Questions, a data discrepancy, or a tool you wish existed — email <MailLink />. Bug reports and feature requests are also welcome
          as GitHub issues on the repository above.
        </P>
      </Section>
    </ProsePage>
  );
}
